services:
    duckdb_fdw0:
        build:
            context: .
            args:
                - POSTGRES_VERSION=17
                - DUCKDB_VERSION=1.4.1
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
            - duckdb_data:/var/lib/postgresql/duckdb
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=qwert
        # depends_on:
        #     - mdata

volumes:
    initdb-scripts:
        driver: local

    pg_data: # Additional volume to mount the SQL script
        driver: local
        driver_opts:
            o: bind
            type: none
            device: data

    duckdb_data:
        driver: local
        driver_opts: 
            o: bind
            type: none
            device: data

